from docxaicorrector.generation.formatting_transfer import *
from docxaicorrector.generation.formatting_transfer import _apply_minimal_caption_formatting as _apply_minimal_caption_formatting
from docxaicorrector.generation.formatting_transfer import _apply_minimal_image_formatting as _apply_minimal_image_formatting
from docxaicorrector.generation.formatting_transfer import _build_output_formatting_diagnostics as _build_output_formatting_diagnostics
from docxaicorrector.generation.formatting_transfer import _is_allowlisted_centered_quote_paragraph as _is_allowlisted_centered_quote_paragraph
from docxaicorrector.generation.formatting_transfer import _is_heading_like_source_paragraph as _is_heading_like_source_paragraph
from docxaicorrector.generation.formatting_transfer import _is_short_non_heading_paragraph as _is_short_non_heading_paragraph
from docxaicorrector.generation.formatting_transfer import _map_source_target_paragraphs as _map_source_target_paragraphs
from docxaicorrector.generation.formatting_transfer import _resolve_direct_alignment_restoration_decision as _resolve_direct_alignment_restoration_decision
