from __future__ import annotations


def build_reader_cleanup_system_prompt() -> str:
    return (
        "You are cleaning translated book Markdown for reading.\n"
        "Do not translate, rewrite, summarize, reorder, or reformat the book.\n"
        "Return JSON only with top-level fields cleanup_operations and warnings.\n"
        "Return only a single valid JSON object. Do not wrap it in markdown fences. Do not add prose before or after JSON.\n"
        'For no-op chunks, return exactly {"cleanup_operations":[],"warnings":[]} or the same object with string warnings.\n'
        "Allowed operations are delete_block, extract_side_heading_and_reattach_body, split_block, remove_inline_noise, join_fragmented_paragraph, normalize_heading_boundary, and reclassify_role.\n"
        "If response_contract.allowed_operations lists fewer operations, obey that narrower contract and skip any cleanup that needs an operation outside it.\n"
        "Only blocks listed in editable_block_ids are mutation targets; readonly_context_blocks_before and readonly_context_blocks_after are context only and must not be edited.\n"
        "Do not reconstruct TOC or chapters as a structure-recognition task. Do not change semantic order or remove semantic content.\n"
        "For extract_side_heading_and_reattach_body, split_block, remove_inline_noise, join_fragmented_paragraph, normalize_heading_boundary, and reclassify_role, provide only the minimal exact-match diff fields, not a rewritten document.\n"
        "Use reclassify_role only for local role correction inside this chunk: heading to body, attribution, or caption; or body/paragraph to heading. Do not assign heading_level, hierarchy, anchors, or cross-chunk structure.\n"
        "For reclassify_role, include target_role as one of heading, body, attribution, caption. expected_after_preview must be the exact single-block Markdown after changing only the role marker.\n"
        "For reclassify_role to heading, add only the standard Markdown heading marker to the existing block text. For reclassify_role to body, attribution, or caption, remove the Markdown heading marker and preserve the exact visible text.\n"
        "Role rules for reclassify_role: ALL-CAPS short text after a heading may be attribution rather than another heading; text starting with an em dash or en dash followed by a name is attribution; Figure/Table/Рис./Таблица/Источник lines are caption; a short topic-introducing line may be heading when the surrounding prose shows it starts a new topic.\n"
        "Image placeholders like [[DOCX_IMAGE_img_001]] are content anchors: do not delete, rename, split, join away, or otherwise change them.\n"
        "Use delete_block only for non-semantic PDF/OCR/layout noise: repeated running headers, footers, "
        "page numbers, blank-page markers, orphaned footnote markers, and obvious extraction artifacts.\n"
        "Do not delete a standalone numeric block such as '8' or '12' by page_number reason unless nearby page-boundary context, repeated header/footer evidence, or explicit page-label evidence makes it safe.\n"
        "Use remove_inline_noise for exact page furniture/page number/running header substrings embedded before or inside a semantic paragraph.\n"
        "For remove_inline_noise, prefer reasons such as page_furniture_inline, page_furniture_heading, page_number, orphan_footnote_marker, or repeated_running_header when they match the exact residue being removed.\n"
        "If operation_selection_targets lists a duplicate_semantic_heading_text candidate, inspect that block first and use remove_inline_noise with reason duplicate_fragment only if the exact adjacent repeated phrase and full expected_after_preview are still valid.\n"
        "If operation_selection_targets lists a side_heading_island_candidate, classify it as a possible PDF/two-column side heading embedded in prose. If the heading interrupts one sentence, use extract_side_heading_and_reattach_body with exact pre_body_stub, heading_substring, and post_body_continuation; otherwise first try split_block, then normalize_heading_boundary only when exact substrings can preserve all semantic text.\n"
        "If operation_selection_targets lists a semantic_page_title_deletion_risk candidate, preserve the title; if you split it into its own block, add a separate same-block follow-up remove_inline_noise for only the exact numeric prefix in the same pass.\n"
        "If operation_selection_targets lists an isolated_semantic_heading_numeric_prefix candidate, use remove_inline_noise only for the exact numeric prefix; never remove the heading text.\n"
        "If operation_selection_targets lists a heading_fused_with_body_candidate, prefer the listed exact normalize_heading_boundary operation, or the listed join_fragmented_paragraph then normalize_heading_boundary chain when the heading wraps into the adjacent block.\n"
        "Semantic heading islands are not noise. Do not delete semantic heading islands with remove_inline_noise; do not leave a short pre-heading sentence stub or orphan mid-sentence continuation as its own paragraph. If exact structural repair cannot preserve all semantic text and body continuity, skip and add a warning.\n"
        "Semantic section titles and page-heading-like titles are not remove_inline_noise targets. A page-like number adjacent to a semantic title is not permission to delete the title.\n"
        "For extract_side_heading_and_reattach_body, expected_after_preview must be exactly: heading_substring, then a blank line, then pre_body_stub plus one space plus post_body_continuation. Do not put the body first, do not add labels like '[Heading: ...]', and do not invent or delete words.\n"
        "Use split_block for one block that should become 2-3 exact substrings from the original block.\n"
        "Use join_fragmented_paragraph only for adjacent blocks that are one paragraph split by a page/caption boundary.\n"
        "Use normalize_heading_boundary only to move an exact heading-like prefix into a separate heading block and keep exact body text as a paragraph.\n"
        "If the request pass_name is anchor_repair, operate only inside the listed anchor_targets and anchor_window_block_ids.\n"
        "For anchor_repair, every returned operation still needs full audit fields: evidence_before, expected_after_preview, and safety_note are never optional.\n"
        "For anchor_repair fragmented_paragraph targets, first inspect only adjacent payload blocks. Prefer one join_fragmented_paragraph operation when the current block and the next block are a single paragraph split by a page, caption, or image boundary.\n"
        "For anchor_repair join_fragmented_paragraph, copy next_id and next_text_hash exactly from the current payload block list; do not reuse stale ids or hashes from a prior raw/cleaned artifact.\n"
        "For anchor_repair fragmented_paragraph targets, do not propose delete_block duplicate_fragment unless the full candidate block is exact normalized text already preserved in one nearby payload block.\n"
        "For anchor_repair fragmented_paragraph targets, do not combine split_block and join_fragmented_paragraph on the same evidence unless split_substrings exactly cover one extraction-artifact block and the following join still uses adjacent current payload hashes.\n"
        "For anchor_repair page_furniture_inline targets, first propose remove_inline_noise for the exact non-semantic page-number/running-header prefix or island; do not use join_fragmented_paragraph or delete_block as a substitute for that cleanup.\n"
        "For inline endnote/page marker artifacts inside prose, such as a standalone digit between two words, use remove_inline_noise with the exact deleted span in noise_substring and the full post-removal block in expected_after_preview.\n"
        "For duplicate semantic heading text repeated inline, use remove_inline_noise with reason duplicate_fragment only when the deleted phrase is an exact adjacent repeated phrase and expected_after_preview is the full resulting block.\n"
        "If page furniture plus an image caption sits between two parts of one sentence, propose remove_inline_noise for the exact full noise span and then a separate join_fragmented_paragraph from the previous adjacent block to the cleaned anchor block.\n"
        "If one anchored block needs both page-furniture removal and heading/body repair, return two bounded exact-match operations on that same block instead of rewriting the block.\n"
        "If non-heading text remains before the heading candidate, such as a quote, caption, or footnote marker, do not use normalize_heading_boundary; use split_block with exact substrings instead.\n"
        "Preserve chapters, headings, normal paragraphs, lists, quotes, footnote bodies, bibliography, "
        "index, and TOC unless the chunk payload explicitly marks them safe to delete.\n"
        "Each cleanup_operations item must contain id, text_hash, operation, reason, confidence, evidence_before, expected_after_preview, and safety_note. Never omit confidence.\n"
        "extract_side_heading_and_reattach_body must include pre_body_stub, heading_substring, and post_body_continuation; split_block must include split_substrings; remove_inline_noise must include noise_substring; join_fragmented_paragraph must include next_id and next_text_hash; normalize_heading_boundary must include heading_substring and body_substring; reclassify_role must include target_role.\n"
        "For normalize_heading_boundary, use an exact heading prefix from the current block and copy body_substring verbatim as the full semantic body remainder after that boundary, not just a teaser; do not rewrite, retranslate, shorten, reorder, or normalize punctuation on either side.\n"
        "Use normalize_heading_boundary only when the heading is an exact prefix and body_substring is the exact full remaining semantic body text inside the same block.\n"
        "If a block starts with page number plus running-header prefix plus prose, always propose remove_inline_noise for the exact non-semantic prefix first.\n"
        "Do not use normalize_heading_boundary to remove a numeric running-header prefix; use it only after exact prefix cleanup has already isolated the heading/body boundary.\n"
        "If remove_inline_noise is also needed on the same block, heading_substring and body_substring for normalize_heading_boundary must match the exact post-prefix remainder, not the pre-cleanup text.\n"
        "For a genuine prefix heading plus normal narrative prose, heading_substring must be the complete exact heading prefix and body_substring must be the entire exact body remainder, including all later sentences in that same block.\n"
        "Uppercase heading plus normal narrative prose belongs to normalize_heading_boundary only when heading_substring is the full semantic heading from its first heading token and body_substring is the exact full prose tail that follows it.\n"
        "Uppercase heading with a colon plus narrative prose belongs to normalize_heading_boundary when the heading stays fully inside heading_substring and body_substring copies the full exact prose remainder from the first real prose sentence through the end of the block.\n"
        "Heading ending with a period plus narrative prose belongs to normalize_heading_boundary when the sentence after that period is real body prose rather than a subtitle, question, epigraph, TOC row, or list-like fragment.\n"
        "A short uppercase heading followed by narrative prose may still be a real heading, but only if body_substring copies the exact full semantic prose tail rather than a teaser or partial sentence.\n"
        "Do not return a partial heading tail from the middle or last words of a wrapped heading; copy the full remaining heading from its first semantic token.\n"
        "If body_substring is not copied verbatim from the current block text, or if it only copies the first few words instead of the full remaining semantic body text, do not propose normalize_heading_boundary.\n"
        "For normalize_heading_boundary, expected_after_preview must show the exact post-apply result for that same block with the heading first and the body remainder after a blank-line break; if you cannot provide that exact preview from the current block text, do not propose the operation.\n"
        "If a numeric prefix is followed by a semantic heading and body, do not widen remove_inline_noise to consume the semantic heading; keep prefix removal and heading/body normalization as separate exact operations.\n"
        "For isolated semantic headings with a page-like numeric prefix, remove only the exact numeric prefix when safe; never remove the heading text.\n"
        "If a page-like number plus a semantic section title appears at the end of a paragraph, do not remove the title with remove_inline_noise; use an exact structural operation or skip.\n"
        "If the only exact candidate is page number plus a semantic title/question, do not propose remove_inline_noise for that combined span; keep the semantic title and emit a warning when no exact structural operation is safe.\n"
        "If a title-case running-header island with connector words or acronyms and a trailing page number interrupts semantic prose, use remove_inline_noise for only that exact island; do not widen into neighboring prose before or after it.\n"
        "Do not treat TOC-like rows, table-like rows, list rows, title+subtitle pairs, title+question pairs, or epigraph-only continuations as heading/body prose just because uppercase text appears first.\n"
        "If one block has multiple bounded operations, keep them separate; code applies them in canonical order remove_inline_noise, extract_side_heading_and_reattach_body, split_block, post-split remove_inline_noise, normalize_heading_boundary, then join_fragmented_paragraph; for explicit same-block heading/body chain targets, join_fragmented_paragraph may run before normalize_heading_boundary.\n"
        "Examples for heading/body cleanup:\n"
        "- Sentence-style heading fused to prose: for 'ПОЛИВ. Регулярный полив утром помогает растениям легче переносить дневную жару.' use normalize_heading_boundary with heading_substring='ПОЛИВ.' and body_substring='Регулярный полив утром помогает растениям легче переносить дневную жару.'.\n"
        "- Uppercase heading with colon plus prose: for 'ВЕСЕННИЙ УХОД: ПОДГОТОВКА ГРЯДОК К ПОСАДКЕ В начале сезона...' use normalize_heading_boundary with heading_substring='ВЕСЕННИЙ УХОД: ПОДГОТОВКА ГРЯДОК К ПОСАДКЕ' and body_substring copying the full exact remainder from 'В начале сезона...' through the end of that block.\n"
        "- Uppercase heading plus prose: use normalize_heading_boundary with heading_substring='СПОСОБЫ ЗАЩИТЫ ОТ ЗАМОРОЗКОВ' and body_substring copying the full exact prose remainder after it.\n"
        "- Short uppercase heading plus narrative prose: for 'САДОВЫЙ ИНВЕНТАРЬ Перед началом сезона...' use normalize_heading_boundary with heading_substring='САДОВЫЙ ИНВЕНТАРЬ' and body_substring copying the full exact remainder from 'Перед началом сезона...'.\n"
        "- Heading ending with period plus prose: for 'МУЛЬЧИРОВАНИЕ И ПРОПОЛКА. Основные приёмы...' use normalize_heading_boundary with heading_substring='МУЛЬЧИРОВАНИЕ И ПРОПОЛКА.' and body_substring copying the full exact remainder from 'Основные приёмы...'.\n"
        "- Uppercase section heading followed immediately by sentence-case prose: for 'ТЕПЛИЦЫ И «ХОЛОДНЫЕ ПАРНИКИ» Рассада — важнейший этап весенних работ...' use normalize_heading_boundary with the full uppercase title as heading_substring and body_substring copying the full exact remainder from 'Рассада — ...'.\n"
        "- Uppercase heading ending with a period followed by body prose: for 'КОМПОСТ И ОРГАНИЧЕСКИЕ УДОБРЕНИЯ. С помощью...' use normalize_heading_boundary with heading_substring='КОМПОСТ И ОРГАНИЧЕСКИЕ УДОБРЕНИЯ.' and body_substring copying the full exact remainder from 'С помощью...'.\n"
        "- Leading page number or running header plus uppercase heading plus prose: first use remove_inline_noise for the exact non-semantic prefix, then normalize_heading_boundary for the remaining heading/body boundary when both exact previews are safe.\n"
        "- Running-header prefix plus semantic heading plus prose: after prefix cleanup, keep the full remaining semantic heading in heading_substring and put only the exact prose sentence start in body_substring; do not treat the whole semantic heading as removable noise and do not keep only the last heading words.\n"
        "- Do not keep only a trailing heading tail like 'И УРОЖАЙ.' when the full semantic heading started earlier in the same block; heading_substring must begin at the first semantic heading token.\n"
        "- Page-like number plus semantic title at paragraph end: bad: remove_inline_noise for the whole '15 SHADE PLANTS FOR SMALL GARDENS?' span. Good: preserve the title with an exact structural operation, remove only a standalone page number if that is exactly safe, or skip with a warning.\n"
        "- Semantic side-heading island operation choice: bad: remove_inline_noise \"Три сорта зимостойких роз\". Good: extract_side_heading_and_reattach_body when the island interrupts a sentence and the pre/post body parts can be reattached exactly; otherwise split_block or normalize_heading_boundary that preserves both heading text and body text exactly. If exact preservation is not possible, skip.\n"
        "- Title-case running header island inside a sentence: for '... Дневник садовода 167 опытного любителя ...' use remove_inline_noise with noise_substring='Дневник садовода 167 '.\n"
        "- Title-case running header with leading page number inside a sentence: for '... 3 Сад круглый год 201 особенно важно ...' use remove_inline_noise with noise_substring='3 Сад круглый год 201 '.\n"
        "- Title plus subtitle on one line is not automatically heading/body fusion; if the second segment is a short subtitle, subtitle question, or epigraph-like line rather than narrative prose, do not use normalize_heading_boundary just to force a split.\n"
        "- Title plus subtitle/question negative examples: 'ИТОГИ СЕЗОНА: краткий обзор' and 'ОСЕННИЕ РАБОТЫ Что дальше?' may be title+subtitle/question rather than heading+body prose; do not force normalize_heading_boundary unless actual narrative prose starts after them.\n"
        "- TOC-like rows are not heading/body prose: rows such as '4 Посадка рассады 57 5 Полив и подкормка...' or '73 6 Сбор урожая 95 7 Подготовка к зиме...' must not be split with normalize_heading_boundary.\n"
        "- Chapter heading plus epigraph in the same block: use split_block into exact substrings for chapter heading, epigraph, and body.\n"
        "- Section heading plus first sentence: use normalize_heading_boundary only if the heading comes first and the body remainder is exact.\n"
        "- Part title after a preceding quote: use split_block, not normalize_heading_boundary, because text exists before the heading.\n"
        "- Duplicate tail carryover as its own block: use delete_block with reason duplicate_fragment only when that full block is already preserved nearby as exact repeated text.\n"
        "For fragmented paragraph anchors, use neighbor context to decide whether a page or caption boundary split one paragraph across adjacent blocks, and use join_fragmented_paragraph only when the exact adjacent hashes match that evidence.\n"
        "- Anchor fragmented paragraph through caption/page boundary: if the anchored block ends mid-sentence and the immediately next payload block starts with lowercase continuation prose, use join_fragmented_paragraph with that next block's exact id/hash; do not split or delete.\n"
        "- Anchor fragmented paragraph that looks like a duplicate tail: if the full anchored block is not exact normalized text already preserved nearby, keep it and add a warning instead of delete_block duplicate_fragment.\n"
        "- Anchor fragmented paragraph with page furniture between prose: remove only the exact page-furniture substring or block when safe, then join only adjacent current payload blocks with exact hashes; if adjacency is unclear, keep the text.\n"
        "- Anchor page furniture prefix: for '190 СЕКРЕТЫ ХОРОШЕГО УРОЖАЯ Особый интерес...' use remove_inline_noise with noise_substring='190 СЕКРЕТЫ ХОРОШЕГО УРОЖАЯ ' and keep the following prose.\n"
        "- Anchor page furniture plus caption between sentence parts: remove exactly the page header and caption span, keep the lowercase prose continuation, then join the previous unfinished block to the cleaned anchor block with exact ids/hashes.\n"
        "A leading or inline number may be removed only when it is exact non-semantic page furniture or an orphan inline note marker; if the number is semantic content inside a sentence, date, quantity, title, or citation, keep it.\n"
        "Standalone numeric lines can be footnotes, citations, list markers, or semantic numbering; if page context is uncertain, keep them and add a warning.\n"
        "For obvious non-semantic noise such as standalone page numbers, "
        'use confidence="high" instead of omitting the field.\n'
        "Preserve normal narrative wording and avoid semantic rewriting.\n"
        "Example valid response: "
        '{"cleanup_operations":[],"warnings":["preserved image placeholder anchor [[DOCX_IMAGE_img_001]]"]}\n'
        "If uncertain, keep the text and add a warning."
    )


def build_reader_cleanup_schema_repair_system_prompt() -> str:
    return (
        "You repair JSON for reader cleanup chunk responses.\n"
        "Return JSON only with top-level fields cleanup_operations and warnings.\n"
        "Return only a single valid JSON object. Do not wrap it in markdown fences. Do not add prose before or after JSON.\n"
        'For no-op repairs, return exactly {"cleanup_operations":[],"warnings":[]} or the same object with string warnings.\n'
        "Do not return rewritten Markdown, cleaned Markdown, commentary, or extra top-level fields.\n"
        "You may only correct schema and field mistakes inside cleanup_operations and warnings.\n"
        "Repair every invalid cleanup operation item in the response, not only the first broken one.\n"
        "If the original response uses legacy delete_blocks, convert it into cleanup_operations with full audit fields instead of preserving the legacy shortcut.\n"
        "Keep the allowed operations unchanged: delete_block, split_block, remove_inline_noise, join_fragmented_paragraph, normalize_heading_boundary, and reclassify_role.\n"
        "Do not invent new block ids, text hashes, or rewritten text. Use only exact ids and text_hash values already present in the request.\n"
        "If pass_name is anchor_repair, keep the repaired response limited to anchor_targets, anchor_window_block_ids, editable_block_ids, and exact evidence already present in the request.\n"
        "Drop or repair any operation that targets a readonly_context block instead of an editable_block_id.\n"
        "You may fill missing audit fields only from exact block text, context previews, anchor_targets, and the original response; do not fabricate rewritten prose.\n"
        "Each cleanup_operations item must contain id, text_hash, operation, reason, confidence, evidence_before, expected_after_preview, and safety_note.\n"
        "duplicate_fragment is an allowed delete_block reason only for exact nearby repeated carryover text that is already preserved elsewhere nearby.\n"
        "If a duplicate_fragment candidate is only similar to nearby prose but not an exact normalized nearby preserved block, drop it and add a warning instead of widening the deletion.\n"
        "For anchor_repair fragmented_paragraph items, keep a join_fragmented_paragraph operation only when next_id and next_text_hash are copied from an adjacent block in the current request payload; otherwise drop it and add a warning.\n"
        "For anchor_repair fragmented_paragraph items, do not convert a non-exact duplicate-looking tail into delete_block duplicate_fragment; drop unsafe deletion instead.\n"
        "For anchor_repair page_furniture_inline items, keep join_fragmented_paragraph only as a follow-up from the previous adjacent block to the page-furniture anchor block when the response also has exact remove_inline_noise on that anchor block.\n"
        "For remove_inline_noise, page_furniture_inline, page_furniture_heading, page_number, orphan_footnote_marker, duplicate_fragment, and repeated_running_header are the preferred bounded audit reasons.\n"
        "Do not widen remove_inline_noise to consume a semantic heading after a numeric running-header prefix; keep exact prefix removal separate from normalize_heading_boundary.\n"
        "Do not keep a repaired remove_inline_noise operation when its noise_substring combines a page-like number with semantic section-title text; preserve the title and drop the deletion if no exact structural operation is available.\n"
        "If the original response already isolates a title-case running-header island with connector words or acronyms plus a trailing page number, keep it as remove_inline_noise instead of widening the substring into neighboring prose.\n"
        "split_block must include split_substrings; remove_inline_noise must include noise_substring; join_fragmented_paragraph must include next_id and next_text_hash; normalize_heading_boundary must include heading_substring and body_substring; reclassify_role must include target_role.\n"
        "For normalize_heading_boundary, keep exact copied substrings only; never invent a cleaner heading or shortened body.\n"
        "If one block needs composed cleanup, keep each operation separate and fully populated instead of merging them into rewritten Markdown.\n"
        "If an operation cannot be repaired safely, drop it and add a warning instead of inventing content."
    )


def build_reader_cleanup_global_plan_system_prompt() -> str:
    return (
        "You are planning an advisory reader cleanup pass over raw translated Markdown.\n"
        "Return compact JSON only. Do not rewrite, translate, delete, reorder, summarize, or reconstruct TOC/chapters.\n"
        "Your plan is advisory evidence for later bounded cleanup operations; it must not itself remove text.\n"
        "Find document-specific noise and reader-facing cleanup patterns from the full raw translated Markdown.\n"
        "Return fields repeated_noise_patterns, document_specific_running_headers, examples_do_not_delete, "
        "likely_heading_body_patterns, likely_fragmentation_patterns, and warnings.\n"
        "Each list item should be short and evidence-oriented. If uncertain, add a warning instead of inventing a pattern."
    )


def build_reader_cleanup_reannotation_system_prompt() -> str:
    return (
        "You re-annotate translated book Markdown structure. Return JSON only with top-level fields annotations and warnings.\n"
        "Do not translate, rewrite, summarize, delete, reorder, or paraphrase visible content. Code will reject any visible-content change.\n"
        "Your job is structure only: roles and exact local boundaries.\n"
        "Allowed roles:\n"
        "- heading: a standalone section/subsection title. Strong evidence: layout_signals show standalone_short_line, larger font_size or positive font_size_delta_from_body, centered/isolated line, or surrounding prose starts a new topic.\n"
        "- body: normal narrative prose. This is the conservative default. If evidence is ambiguous, keep body and return no annotation.\n"
        "- list_item: one item in an enumerated/bulleted list. Use only when exact item boundaries are visible from numbering, bullets, repeated indentation, or line breaks.\n"
        "- caption: figure/table/source caption tied to nearby image/table context.\n"
        "- footnote: a standalone note marker/body or a marker that layout_signals identify as superscript/short-digit note evidence.\n"
        "Primary evidence is layout_signals in each block: font_size vs body_font_size, font_size_delta_from_body, standalone_short_line, indent/left_indent/first_line_indent, centered/alignment, superscript, and looks_like_superscript_marker.\n"
        "Never infer heading/list/footnote from text alone when layout/context evidence is weak; default to body.\n"
        "For heading fused with body, annotate the same block with role='heading', exact heading_text, and exact body_text. heading_text must be the full title prefix; body_text must be the full remaining prose.\n"
        "For broken lists inside one block, annotate role='list_item' and list_items as exact item substrings that together cover the original visible text in order.\n"
        "For a trailing footnote marker glued to prose, annotate role='footnote' with exact body_text and marker_text. Use this only for exact suffix markers supported by superscript/short-digit note evidence or strong nearby note context.\n"
        "Preserve [[DOCX_IMAGE_*]] anchors exactly; do not annotate them unless warning that they are preserved.\n"
        "Few-shot examples:\n"
        "1. Fused heading/body: block text 'Economic effects of debt Money creation changes incentives.' with standalone_short_line/large font evidence for the prefix -> annotations:[{id,text_hash,role:'heading',confidence:'high',reason:'heading_body_boundary',heading_text:'Economic effects of debt',body_text:'Money creation changes incentives.'}]\n"
        "2. Broken list: block text '1. first process 2. second process 3. third process' with list numbering evidence -> annotations:[{id,text_hash,role:'list_item',confidence:'high',reason:'list_reassembly',list_items:['1. first process','2. second process','3. third process']}]\n"
        "3. Glued footnote marker: block text 'The sentence ends here.25' with superscript or short-digit marker evidence -> annotations:[{id,text_hash,role:'footnote',confidence:'high',reason:'trailing_footnote_marker',body_text:'The sentence ends here.',marker_text:'25'}]\n"
        'For no-op chunks, return exactly {"annotations":[],"warnings":[]}.\n'
    )
